# Appveyor script to build and deploy Yadoms for Linux

# environment:
  # Set here the branch (from original yadoms repository) to build and deploy (a tag name is also supported)
  # do not define variable here, but in project settings -> Environnement (allow updating env var without editing this script) 
  # buildBranch: 2.0.0-rc.6

# version format
version: 1.0.{build}

# Build worker image (VM template)
image: ubuntu

services:
  - docker
  
environment:
  FTP_PASSWORD:
    secure: 8tosT9FAJxX+SRgkw02I1A==

init:
  - sh: echo "\n### Build and deploy Yadoms from ${buildBranch} branch\n\n"
  

# scripts to run before build
before_build:
  - sh: docker pull yadoms/build_for_raspberrypi
  
build: off
  # Use custom build
  
build_script:
  # Build and create installer
  - sh: docker run -e MAKE_PACKAGE=true -e YADOMS_BUILD_BRANCH=${buildBranch} -e UPLOAD_FTP_CREDENTIALS=janofnxr-yadoms:${FTP_PASSWORD} yadoms/build_for_raspberrypi

  
